### PR TITLE
Bump node version and fix deprecation warnings

### LINKED ISSUE #149: Deprecated save-state
Hi - this is a great action and exactly what I'm looking for. 

I did notice the below warnings when running the action: 

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### PR DESCRIPTION
**Pull request by rmichalak**
This PR:
- upgrades Node version to 16
- updates 'core' package which also removes deprecation warnings for `saveState` function
- updates tests accordingly
- updates `ncc`
- updates actions to remove deprecation messages

Fixes #149

### CODE REVIEW

**Review by jmealo — APPROVED** [review]
:+1: LGTM

**Review by jmealo — APPROVED** [review]
:+1: LGTM

**Comment by jmealo** [comment]
@rmichalak Thanks Robert! Looks great. I went ahead and merged it :)

**Comment by rmichalak** [comment]
@jmealo Thanks!
Can you please release a new version now?

**Comment by jmealo** [comment]
Sure thing. Will take a look tonight. @themightychris

**Comment by jmealo** [comment]
@rmichalak `v1.0.1` pushed. Thanks again for your PR!

**Comment by jmealo** [comment]
@rmichalak try `v1.0.3`

**Pull request merged**
