### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
Fixes the warnings at the bottom right of
https://github.com/JarvusInnovations/background-action/actions/runs/8310867573

* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

Also see:
* #184

@Multimo, @marcinlesek  Your reviews, please

### CODE REVIEW

**Comment by marcinlesek** [comment]
This looks good to me @cclauss, but I don't have permission to give approves here. 😉 You need to call @ryon and @themightychris as they are people in `JarvusInnovations` organisation.

**Review by marcinlesek — APPROVED** [review]

**Comment by cclauss** [comment]
@jmealo Your review, please.

**Comment by jmealo** [comment]
@cclauss: Looks good to me. Thanks for the PR. If the tests run I'll merge.

**Comment by cclauss** [comment]
Generated:
* #190

**Pull request merged**
