### PR TITLE
feat: upgrade from node 16 to 20

### PR DESCRIPTION
**Pull request by Multimo**
https://github.com/JarvusInnovations/background-action/issues/185

Upgrades node to use v20 and also upgrades some of the internal actions to v4 so that they also use v20. 

Not quite sure how to test this so any direction here would be helpful :)

### CODE REVIEW

**Comment by cclauss** [comment]
You can automate most of these changes by using GitHub's Dependabot.
* https://github.com/jayvdb/nose3/pull/7/files

**Comment by marcinlesek** [comment]
Thank you @Multimo 🎉 

@ryon @themightychris can you folks please take a look on that? Now all Actions shows warning about this deprecation. 🙏🏻

**Review by cclauss — APPROVED** [review]

**Review by marcinlesek — APPROVED** [review]

**Comment by till** [comment]
Can haz merge? 😄

**Comment by jmealo** [comment]
@till: I need to check with @themightychris that the hologit part works with Node 20, if so we should be good to merge this

**Comment by jmealo** [comment]
@till: @cclauss: I checked with @themightychris, the changes you made are correct, however, we need to push an update for `hologit` that supports Node 20 for them to work. I can't commit to when this would happen but he's aware of the issue. Once `hologit` supports Node 20, we should be able to merge this.

**Comment by till** [comment]
Thank you very much!

**Pull request merged**
